### ISSUE TITLE
Wrong clarification in .eslintrc

### ISSUE THREAD

**Issue by andresgnlez** [Vizzuality/front-end-scaffold#1]
https://github.com/Vizzuality/front-end-scaffold/blob/8a428094d46d3dd4d3a24581e52d0525417e5b82/.eslintrc.js#L26

I think this comment is not completely accurate as this suggestion comes from [the React team](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform) and applies to any project using React, independently of the framework used.

I suggest replacing the comment pointing to the link mentioned above.

**Comment by davidsingal** [comment]
I do agree with your suggestion. Please, could you create a PR?
