### ISSUE TITLE
robots.txt policy

### ISSUE THREAD

**Issue by andresgnlez** [Vizzuality/front-end-scaffold#116]
Based on the [article](https://www.searchviu.com/en/robots-txt-staging-environment/) Álvaro shared, shall we change [our robots.txt policy](https://github.com/Vizzuality/front-end-scaffold/blob/main/public/robots.txt)? Right now, any production application will deploy with robots disabled which may impact SEO results if the file is not changed consciously.

I think like the article: staging/preview sites are development exceptions and should be treated as if. There are better ways to stop robots from crawling and avoid modifying `robots.txt` per environment.

**Comment by mbarrenechea** [comment]
https://github.com/vercel/examples/tree/main/edge-functions/basic-auth-password
