### ISSUE TITLE
Improve documentation for env variables

### ISSUE THREAD

**Issue by davidsingal** [Vizzuality/front-end-scaffold#32]
Due to we have some issues managing front end projects via Docker, and to facilitate the work to our colleagues devops. [Here more context](https://vizzuality.slack.com/archives/C0ZU0N589/p1647448870620989)
We need to add better information about the env variables we use in the project. So we need the next:

1. Describe the use of every variable as we are doing here: https://github.com/Vizzuality/marxan-cloud/blob/0b9e41a4f992ea9941fb74bd761344eb991fbd16/app/README.md#L3
2. Add a text specifying which variables are required in building time and which on running time.
3. Keep updated a .env.sample as much as possible

**Comment by tiagojsag** [comment]
also: for vars that hold URLs, please write down if the protocol should be included or not. A "nice to have" is adding an example of said value.

**Comment by davidsingal** [comment]
There is a rule that could help to facilitate the docs, only `NEXT_PUBLIC_` env variables are required on building time. The rest are needed on running time.
