### ISSUE TITLE
Do we need next-optimizided-images?

### ISSUE THREAD

**Issue by davidsingal** [Vizzuality/front-end-scaffold#39]
Part of the agreement with the designers is: they are going to provide the images already optimized in Figma. So, we shouldn't optimize the images.

Also, should we use `next/images`? https://vercel.com/docs/concepts/image-optimization/limits-and-pricing It seems like there some limits

**Comment by mbarrenechea** [comment]
we are using `next-optimizided-images` for dealing (in most cases) with icons/svgs. It add the `sprite-svg-loader` and let you import svg directly in your components/containers and add them to the svg sprite. You can disable the optimization of the images with a simple attribute in the `next.config.js` file (as we have right now). 

```
module.exports = withPlugins(
  [
    withOptimizedImages({
      optimizeImages: false,
    }),
  ],
  nextConfig
);
```

We can discuss if it's really needed or not. In my opinion, I would leave it as it is, we have the power o use it or not. Could we import those libraries separately? SURE. Do we need to do that? IMO no

**Comment by anamontiaga** [comment]
As we have discussed in frontismos, the use of CDNs for image optimization could be investigated.

**Comment by andresgnlez** [comment]
`next-optimized-images` is ditched in https://github.com/Vizzuality/front-end-scaffold/pull/106 as it is not maintained anymore and `svg-sprite-loader` is replacing it so I think we can close this issue now @davidsingal
