### ISSUE TITLE
Should we move to `next/lint`?

### ISSUE THREAD

**Issue by davidsingal** [Vizzuality/front-end-scaffold#41]
Right now we are using Airbnb `eslint` configuration but NextJs provides one officially. Should we move to it? In Landgriffon we tested and it's working fine.

**Comment by anamontiaga** [comment]
As we have discussed in frontismos, if the current configuration works properly, why change it?

**Comment by davidsingal** [comment]
And why not? It's working, yes. But is the most optimal way to apply eslint? This is the discussion. airbnb-eslint was created for javascript, and then the plugin for typescript applies new rules overriding and adding new libraries to make it compatible. Additionally, we add rules for next specific, something we have to maintain, but it's not a big problem.
Using next-eslint, we can reduce the number of libraries for linting, easily add typescript support, we don't have to keep updated and only maintain our own rules.
It's true is not a priority to change it, but we should analyse better our implementations, even if it's already working because is there a space for improvement we should explore. jQuery also works but we change it.
