### ISSUE TITLE
TailwindCSS: remove `line-clamp` custom plugin.

### ISSUE THREAD

**Issue by andresgnlez** [Vizzuality/front-end-scaffold#56]
With the [official implementation of line-clamp](https://github.com/tailwindlabs/tailwindcss-line-clamp) for TailwindCSS [installed](https://github.com/Vizzuality/front-end-scaffold/blob/main/package.json#L54), I think it doesn't make any sense to keep our [custom implementation](https://github.com/Vizzuality/front-end-scaffold/blob/main/src/lib/tailwind/line-clamp.js) of it and can be safely removed.

**Comment by mbarrenechea** [comment]
it can be safely removed, no worries
