### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by mbarrenechea** [Vizzuality/front-end-scaffold#79]
https://codesandbox.io/s/gallant-sea-rcg43b?file=/src/Select.tsx

Should we move away from downshift and create a couple of simple selects? One multiple and another simple?

**Comment by anamontiaga** [comment]
As we have talked about in frontismos, we will talk to the designers to see the possibility of using simpler solutions and avoid having to use select complex components.

This library should be an option: 
[Headlessui](https://headlessui.com/react/listbox)
