### ISSUE TITLE
import type isn't valid in my typescript set up

### ISSUE THREAD

**Issue by pablopareja** [Vizzuality/front-end-scaffold#8]
https://github.com/Vizzuality/front-end-scaffold/blob/9f69501e9c6b1417693a548608ce597c334768d2/pages/_app.tsx#L2

![image](https://user-images.githubusercontent.com/545342/119125735-70e32e80-ba32-11eb-87a1-59899f6c838c.png)

@davidsingal ☝️

**Comment by davidsingal** [comment]
It's not related to your Typescript setup. It seems a conflict with the Prettier plugin in your Visual Code. @pablopareja Do you think makes sense to add a prettier config file??

**Comment by pablopareja** [comment]
@davidsingal Oh I see 👍 
That'd be useful at least for me :)
